export enum StoryPointCommand {
  RESET = 'RESET',
  SUBMIT_RSVP = 'SUBMIT_RSVP',
  START_SEND_CHOICES = 'START_SEND_CHOICES',
  BACK_UNLOCK = 'BACK_UNLOCK',
  GAME_OVER = 'GAME_OVER',
  ENTERED_NAME = 'ENTERED_NAME',
  SONG_OUTDOOR = 'SONG_OUTDOOR',
  SONG_ENTRY = 'SONG_ENTRY',
  SONG_CEREMONY = 'SONG_CEREMONY',
  SONG_PARTYAMBIENCE = 'SONG_PARTYAMBIENCE',
  SONG_DANCE = 'SONG_DANCE',
}
